import type { CandidatePlatform } from "@/lib/types";

/** 50 candidate platforms modeled after hireEZ-style open-web sourcing coverage. */
export const CANDIDATE_PLATFORMS: CandidatePlatform[] = [
  {
    id: "linkedin",
    name: "LinkedIn",
    category: "professional",
    status: "live",
    description: "Professional network profiles and career histories.",
    homepage: "https://www.linkedin.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "github",
    name: "GitHub",
    category: "developer",
    status: "live",
    description: "Engineering contributions, languages, and open-source activity.",
    homepage: "https://github.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "developer",
    status: "live",
    description: "DevOps and engineering portfolio signals.",
    homepage: "https://gitlab.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "developer",
    status: "live",
    description: "Repository activity for software teams.",
    homepage: "https://bitbucket.org",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    category: "developer",
    status: "live",
    description: "Technical Q&A reputation and specialty tags.",
    homepage: "https://stackoverflow.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "kaggle",
    name: "Kaggle",
    category: "developer",
    status: "live",
    description: "Data science competitions, notebooks, and datasets.",
    homepage: "https://www.kaggle.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "devto",
    name: "Dev.to",
    category: "developer",
    status: "live",
    description: "Engineering writing and community expertise.",
    homepage: "https://dev.to",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "hashnode",
    name: "Hashnode",
    category: "developer",
    status: "beta",
    description: "Developer blogs and technical thought leadership.",
    homepage: "https://hashnode.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "hackerrank",
    name: "HackerRank",
    category: "developer",
    status: "live",
    description: "Coding challenge performance and skill badges.",
    homepage: "https://www.hackerrank.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "leetcode",
    name: "LeetCode",
    category: "developer",
    status: "beta",
    description: "Algorithm practice and contest standings.",
    homepage: "https://leetcode.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "dribbble",
    name: "Dribbble",
    category: "design",
    status: "live",
    description: "Product and visual design portfolios.",
    homepage: "https://dribbble.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "behance",
    name: "Behance",
    category: "design",
    status: "live",
    description: "Creative portfolios across design disciplines.",
    homepage: "https://www.behance.net",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "carbonmade",
    name: "Carbonmade",
    category: "design",
    status: "planned",
    description: "Designer portfolio hosting.",
    homepage: "https://carbonmade.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "awwwards",
    name: "Awwwards",
    category: "design",
    status: "beta",
    description: "Awarded web design and creative directors.",
    homepage: "https://www.awwwards.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "google_scholar",
    name: "Google Scholar",
    category: "academic",
    status: "live",
    description: "Publications, citations, and research topics.",
    homepage: "https://scholar.google.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "researchgate",
    name: "ResearchGate",
    category: "academic",
    status: "live",
    description: "Academic collaboration and paper graph.",
    homepage: "https://www.researchgate.net",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "orcid",
    name: "ORCID",
    category: "academic",
    status: "live",
    description: "Persistent researcher identifiers and works.",
    homepage: "https://orcid.org",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "ieee_xplore",
    name: "IEEE Xplore",
    category: "academic",
    status: "beta",
    description: "Engineering and computing publications.",
    homepage: "https://ieeexplore.ieee.org",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "acm_dl",
    name: "ACM Digital Library",
    category: "academic",
    status: "beta",
    description: "Computing research authorship.",
    homepage: "https://dl.acm.org",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "pubmed",
    name: "PubMed",
    category: "academic",
    status: "live",
    description: "Biomedical literature authorship.",
    homepage: "https://pubmed.ncbi.nlm.nih.gov",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "healthgrades",
    name: "Healthgrades",
    category: "healthcare",
    status: "live",
    description: "Clinician directories and specialties.",
    homepage: "https://www.healthgrades.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "doximity",
    name: "Doximity",
    category: "healthcare",
    status: "live",
    description: "Physician network and credentials.",
    homepage: "https://www.doximity.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "zocdoc",
    name: "Zocdoc",
    category: "healthcare",
    status: "beta",
    description: "Patient-facing clinician listings.",
    homepage: "https://www.zocdoc.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "npi_registry",
    name: "NPI Registry",
    category: "healthcare",
    status: "live",
    description: "US healthcare provider identifiers and taxonomy.",
    homepage: "https://npiregistry.cms.hhs.gov",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "ratemds",
    name: "RateMDs",
    category: "healthcare",
    status: "planned",
    description: "Physician profiles and patient feedback signals.",
    homepage: "https://www.ratemds.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "indeed",
    name: "Indeed",
    category: "job_board",
    status: "live",
    description: "Active and resume-based job seekers.",
    homepage: "https://www.indeed.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "glassdoor",
    name: "Glassdoor",
    category: "job_board",
    status: "live",
    description: "Company reviews and candidate intent signals.",
    homepage: "https://www.glassdoor.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "wellfound",
    name: "Wellfound",
    category: "job_board",
    status: "live",
    description: "Startup talent and founder/operator profiles.",
    homepage: "https://wellfound.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "dice",
    name: "Dice",
    category: "job_board",
    status: "live",
    description: "Technology contractor and full-time talent.",
    homepage: "https://www.dice.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "monster",
    name: "Monster",
    category: "job_board",
    status: "live",
    description: "Broad-market resume database.",
    homepage: "https://www.monster.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "ziprecruiter",
    name: "ZipRecruiter",
    category: "job_board",
    status: "beta",
    description: "Marketplace of active applicants.",
    homepage: "https://www.ziprecruiter.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "otta",
    name: "Otta",
    category: "job_board",
    status: "beta",
    description: "Startup and scale-up candidate marketplace.",
    homepage: "https://otta.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "remoteok",
    name: "Remote OK",
    category: "job_board",
    status: "live",
    description: "Remote-first candidate intent.",
    homepage: "https://remoteok.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "weworkremotely",
    name: "We Work Remotely",
    category: "job_board",
    status: "live",
    description: "Distributed workforce talent pool.",
    homepage: "https://weworkremotely.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "handshake",
    name: "Handshake",
    category: "job_board",
    status: "live",
    description: "Early-career and campus talent.",
    homepage: "https://joinhandshake.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "builtin",
    name: "Built In",
    category: "job_board",
    status: "beta",
    description: "Tech ecosystem city-market talent.",
    homepage: "https://builtin.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "xing",
    name: "XING",
    category: "professional",
    status: "live",
    description: "DACH-region professional network.",
    homepage: "https://www.xing.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "twitter",
    name: "X (Twitter)",
    category: "social",
    status: "live",
    description: "Public professional presence and topic expertise.",
    homepage: "https://x.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "medium",
    name: "Medium",
    category: "social",
    status: "live",
    description: "Long-form writing and domain authority.",
    homepage: "https://medium.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "substack",
    name: "Substack",
    category: "social",
    status: "beta",
    description: "Independent writers and industry analysts.",
    homepage: "https://substack.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "youtube",
    name: "YouTube",
    category: "social",
    status: "beta",
    description: "Creators and technical educators.",
    homepage: "https://www.youtube.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "meetup",
    name: "Meetup",
    category: "community",
    status: "live",
    description: "Local community organizers and speakers.",
    homepage: "https://www.meetup.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    category: "community",
    status: "live",
    description: "Builders, makers, and launch founders.",
    homepage: "https://www.producthunt.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "hackernews",
    name: "Hacker News",
    category: "community",
    status: "live",
    description: "Startup and engineering discussion footprint.",
    homepage: "https://news.ycombinator.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "reddit",
    name: "Reddit",
    category: "community",
    status: "beta",
    description: "Niche community expertise signals.",
    homepage: "https://www.reddit.com",
    supportsSearch: true,
    supportsEnrichment: false,
  },
  {
    id: "crunchbase",
    name: "Crunchbase",
    category: "identity",
    status: "live",
    description: "Founder and operator company affiliations.",
    homepage: "https://www.crunchbase.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "levels_fyi",
    name: "Levels.fyi",
    category: "identity",
    status: "beta",
    description: "Compensation and level benchmarking signals.",
    homepage: "https://www.levels.fyi",
    supportsSearch: false,
    supportsEnrichment: true,
  },
  {
    id: "uspto",
    name: "USPTO Patents",
    category: "identity",
    status: "live",
    description: "Inventor records and patent assignees.",
    homepage: "https://www.uspto.gov",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "personal_sites",
    name: "Personal Sites",
    category: "identity",
    status: "live",
    description: "Portfolio sites and public resumes on the open web.",
    homepage: "https://example.com",
    supportsSearch: true,
    supportsEnrichment: true,
  },
  {
    id: "ats_rediscovery",
    name: "ATS Rediscovery",
    category: "identity",
    status: "live",
    description: "Prior applicants and talent already inside your ATS.",
    homepage: "internal://ats",
    supportsSearch: true,
    supportsEnrichment: true,
  },
];

export function getPlatformById(id: string): CandidatePlatform | undefined {
  return CANDIDATE_PLATFORMS.find((platform) => platform.id === id);
}

export function listLivePlatforms(): CandidatePlatform[] {
  return CANDIDATE_PLATFORMS.filter((platform) => platform.status !== "planned");
}
